# Generated by Django 5.0.1 on 2024-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=200)),
                ('patient_number', models.IntegerField(max_length=10)),
                ('patient_address', models.CharField(max_length=200)),
                ('patient_admit', models.BooleanField(default=True)),
                ('patient_ward', models.CharField(max_length=10)),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=200)),
                ('staff_number', models.IntegerField(max_length=10)),
                ('staff_address', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_id', models.CharField(max_length=200)),
                ('doctor_number', models.IntegerField(max_length=10)),
                ('doctor_address', models.CharField(max_length=200)),
            ],
        ),
    ]
