# Generated by Django 5.0.1 on 2024-01-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctor_address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='doctor_number',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='staff_address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='staff_number',
        ),
    ]
